[keys.normal]
# Search for word under cursor
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

[keys.normal."space"]
q = ":reflow"

[keys.select."space"]
q = ":reflow"

[editor]
end-of-line-diagnostics = "hint"
line-number = "relative"
rulers = [80, 100, 120]

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
newline = "all"

[editor.whitespace.characters]
newline = "↩"

[editor.inline-diagnostics]
cursor-line = "hint"
